# Image source: https://github.com/skpr/containers/tree/master/php/fpm
ARG PHP_VERSION=8.0
FROM skpr/php-fpm:${PHP_VERSION}-dev-v2-latest AS php-fpm

USER root
RUN echo -e "\nblackfire.agent_socket=tcp://blackfire:8707" >> /etc/php/conf.d/01_blackfire.ini

USER skpr
