FROM skpr/php-cli:7.4-1.x-xdebug AS php-cli-xdebug

USER root
RUN echo -e "\nblackfire.agent_socket=tcp://blackfire:8707" >> /etc/php/conf.d/01_blackfire.ini
RUN echo -e "\nxdebug.remote_host=host.docker.internal" >> /etc/php/conf.d/50_dev.ini
USER skpr
